### ISSUE TITLE
The Node.remove call generates side effects

### ISSUE THREAD

**Issue by GianlucaGuarini** [WebReflection/domdiff#21] opened 2020-01-03 10:29 UTC
The internal call to [`Node.remove`](https://github.com/WebReflection/domdiff/blob/93f9e6c99abb22207f4ba3eb77716485692cfbd1/esm/utils.js#L371) might generate side effects. Can you consider a way to disable it via settings?

**Comment by WebReflection** [comment] 2020-01-03 10:39
can you give me an example? the code fallback already to `parentNode.removeChild` ... maybe this is a duplicate of this one? https://github.com/WebReflection/hyperHTML/issues/383

**Comment by GianlucaGuarini** [comment] 2020-01-03 11:15
@WebReflection sure, I have made a simple custom element example https://plnkr.co/edit/uy1wGAxFBp2vN8dKWON3?p=preview

**Comment by WebReflection** [comment] 2020-01-03 11:18
so the concept is the same of the other issue I've mentioned, if you overwrite inherited methods, you gonna have issues. If you override `removeChild`, or `append`, or any other method in the `HTMLElement` prototype could have issues.

It's true that `domdiff` could be defensive and use only `Node.prototype` trapped methods to work with all nodes, but are you willing to lose performance for that?

**Comment by kaste** [comment] 2020-01-03 11:23
Isn't that a general footgun.  If you send me that CustomElement, I as a user of your CE have the expectation that I can use it like any other HTMLElement/Node. It is maybe an enhanced version of such an element.  Implementing an own `remove` method which does something completely different is not expected OOP-style programming, is it?

**Comment by GianlucaGuarini** [comment] 2020-01-03 11:27
I think the problem is bigger than that. CEs accept attributes that can be converted to Node properties (see demos here https://custom-elements-everywhere.com/).
Now if we do something like:

```html
<my-li remove={ someCallback }/>
```
This will override the `Node.prototype.remove`. At this point I think this is a platform issue that can not be addressed here :(

**Comment by WebReflection** [comment] 2020-01-03 11:27
@kaste exactly my point. `append` instead of `add` would break the HTMLELement contract too, and one could also create a `parentNode` getter that would break the same contract.

This has been discussed already and flagged as _wont'f fix_, as any method / accessor, once overwritten, can cause side effects in the wild, so it's not a _domdiff_ specific issue.

However, I will one day compare performance trapping primitives that would work no matter what, but I am sure performance will be worse.

Also worth noting, as nobody would create a `querySelectorAll` overwrite on a generic element, every other method should follow the same rule, imho.

**Closed** 2020-01-03 11:28 UTC

**Comment by WebReflection** [comment] 2020-01-03 11:30
@GianlucaGuarini about this:

> see demos here https://custom-elements-everywhere.com/

all _domdiff_ based libraries pass that test 100% so I am not sure if the example is valid,  but if they asked to shadow inherited method (I can't remember as I've written those tests ages ago) then it's a test-case issue they should address, as it's suggesting bad practices.

**Comment by kaste** [comment] 2020-01-03 13:06
If you override, you must call _super_.  That's just an OOP rule.  If you trap primitives, you get 1 out of 100000 users which opens an issue why their perfectly fine  *remove* method doesn't get called.

**Comment by WebReflection** [comment] 2020-01-03 13:57
Yup, but I think a post/gist explaining common Custom Elements _donts_ could help anyway ...and for this specific use case I'd suggest using `drop(...)` instead.
