### ISSUE TITLE
Help: How to best utilize domdiff to render long markup fragments

### ISSUE THREAD

**Issue by SMotaal** [WebReflection/domdiff#9] opened 2018-10-07 10:47 UTC
I've been highly inspired by your ideas regarding dom performance which led to me to rethink a lot of the existing abstractions, like [markup](https://github.com/SMotaal/experimental/tree/master/markup).

I am hitting the point where "[Virtual scrolling for long document fragments](https://github.com/SMotaal/experimental/issues/1)" is needed, and I am not sure how to best approach this.

domdiff seems like a good fit so I hope you can help me figure out how to go from a long document fragment to a virtually "smooth" scrolling one using domdiff.

Thanks 👍

**Comment by WebReflection** [comment] 2018-10-08 09:59
not sure I understand your goal, but I'm developing these days this sort of component:
https://webreflection.github.io/eyeo/custom-elements/smoke/io-filter-table.html

the table could render hundred thousand items without a sweat, and it's fully [hyperHTML](https://github.com/WebReflection/hyperHTML) based (in case you didn't know, hyperHTML uses domdiff).

### How to create infinite lists

  * you need to keep the row position, and the scroll one too (or relate both somehow)
  * you need to know the length of each row, at least each row you have rendered, theoretically each row you have previously rendered too if you want to have a meaningful scrollbar
  * you show the row before, each row needed to cover the visible area, the row after

Last point is to give you room for smoother scrolling.

Now, all this is **very complex**, but at least you know the primitives needed to obtain that.

If each row has fixed length, things are easier and probably faster too.

I am closing this since this is not a bug or anything related to domdiff, domdiff just provides the best way to keep appending sequential rows, removing them, or sorting them asc/desc, etc etc ... the amount of rows, and which row you need to render, won't ever land in this library since it's out of scope.

**Closed by WebReflection** 2018-10-08 09:59 UTC
